import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'node:path';
import type { IncomingMessage } from 'node:http';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';

const apiGeneratedDir = path.resolve(__dirname, '../../apps/api/src/generated');
const apiSpaShellPath = path.resolve(apiGeneratedDir, 'spa-shell.ts');

const apiTarget = 'http://localhost:8787';

// `/search` and `/snippets` are both SPA routes and API prefixes. Document
// navigations (Accept: text/html) must keep serving index.html; only data
// fetches proxy to the worker. `/users` needs no bypass: no SPA route shares
// the prefix (profiles live at `/:username`).
function apiProxy({ spaFallback = false }: { spaFallback?: boolean } = {}) {
  return {
    target: apiTarget,
    changeOrigin: true,
    ...(spaFallback && {
      bypass: (req: IncomingMessage) => (req.headers.accept?.includes('text/html') ? '/index.html' : undefined),
    }),
  };
}

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    {
      name: 'spa-shell-embed',
      closeBundle() {
        const indexPath = path.resolve(__dirname, 'dist/index.html');
        if (!existsSync(indexPath)) {
          console.warn('spa-shell-embed: dist/index.html not found, skipping');
          return;
        }
        const html: string = readFileSync(indexPath, 'utf8');
        const output: string = `// Auto-generated by Vite build plugin - DO NOT EDIT.\nexport const SPA_HTML: string = ${JSON.stringify(html)};\n`;
        if (!existsSync(apiGeneratedDir)) {
          mkdirSync(apiGeneratedDir, { recursive: true });
        }
        writeFileSync(apiSpaShellPath, output);
      },
    },
  ],
  server: {
    proxy: {
      '/user': apiProxy(),
      '/users': apiProxy(),
      '/repos': apiProxy(),
      '/search': apiProxy({ spaFallback: true }),
      '/snippets': apiProxy({ spaFallback: true }),
      '/realtime': {
        target: 'http://localhost:8787',
        changeOrigin: true,
        ws: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
});
