// Edge-Git Env shape for isolated package typechecks.
// Apps additionally include worker-configuration.d.ts (generated by
// `wrangler types`); bindings are `any` here so `env.DB` / `env.REPO` /
// `env.CRON_TASKS` are usable without @cloudflare/workers-types.
declare global {
  interface Env {
    DB: any;
    REPO: any;
    CRON_TASKS: any;
    DEBUG_MODE?: string;
    DEV_AUTH_EMAIL?: string;
    DEMO_MODE?: string;
    POLICY_AUD?: string;
    TEAM_DOMAIN?: string;
    SITE_URL?: string;
    SERVE_SPA_FROM_WORKER?: string;
    MAX_REPOS_PER_USER?: string;
    MAX_TOKENS_PER_USER?: string;
    MAX_TOKEN_EXPIRY_DAYS?: string;
    MAX_PACK_OBJECTS?: string;
    GIT_CACHE_TTL_SECONDS?: string;
    MAX_FETCH_WANTS?: string;
    MAX_FETCH_HAVES?: string;
    MAX_PUSH_COMMANDS?: string;
    MAX_PACK_BYTES?: string;
    MAX_FETCH_BODY_BYTES?: string;
    MAX_MERGE_DIFF_FILES?: string;
    BACKGROUND_TASK_RUN_RETENTION_DAYS?: string;
    AUDIT_LOG_RETENTION_DAYS?: string;
  }

  type CloudflareEnv = Env;
}

export {};
