packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260915.1'

patchedDependencies:
  dofs@0.1.0: patches/dofs@0.1.0.patch
