export { IsoGitFs } from './IsoGitFs';
export { ErrorNormalizer, ErrorWithCode, normalizePath } from './ErrorNormalizer';
export { GitService, PackLimitError } from './GitService';
export { RefService } from './RefService';
export { ObjectReader } from './ObjectReader';
export { PackCollector } from './PackCollector';
export { HistoryService } from './HistoryService';
export { MergeService } from './MergeService';
export { computeHunks, diffText, DIFF_CONTEXT_LINES, MAX_DIFF_LINES_PER_FILE } from './DiffHunks';
export type { DiffHunk, DiffLine, DiffLineKind } from './DiffHunks';
export type { RefUpdateResult } from '@edge-git/git-protocol';
export { Fs as DofsFs } from 'dofs';
